demo2/demo2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.http import HttpResponse



urlpatterns = [
    path('admin/', admin.site.urls),
    url('vote/',include('vote.urls',namespace='vote')),

]

demo2/vote/urls.py
from django.conf.urls import url
from . import views


app_name="vote"

urlpatterns =[
    url(r"^login/$",views.login,name="login"),
    url(r"^logout/$",views.logout,name="logout"),
    url(r"^register/$",views.register,name="register"),
    url(r"^index/$",views.index,name="index"),
    url(r"^list/$",views.list,name="list"),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^result/(\d+)/$',views.result,name='result'),
    url(r'^suggest/$',views.suggest,name='suggest'),
    # .*?  匹配所有
    url(r'^active/(.*?)/$',views.active,name='active'),
    url(r'^verify/$',views.verify,name='verify'),
    url(r'^checkuser/$',views.checkuser,name='checkuser'),
    url(r'^change_pwd',views.change_pwd,name='change_pwd'),
]

demo2/vote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class VoteInfo(models.Model):

    matter=models.CharField(max_length=20,verbose_name="投票问题")
    choose1 = models.CharField(max_length=10,verbose_name="选项1")
    choose2 = models.CharField(max_length=10,verbose_name="选项2")
    choose1vote = models.IntegerField(default=0)
    choose2vote = models.IntegerField(default=0)

    def __str__(self):
        return self.matter

class MyUser(User):
    url = models.URLField(blank=True, null=True, default="http://www.baidu.com")
    class Meta():
        verbose_name = "用户"
        verbose_name_plural = verbose_name

demo2/vote/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import VoteInfo,MyUser
from django.views.generic import View
from django.contrib.auth import authenticate,login as lgi,logout as lgo
from .util import checklogin
from django.conf import settings
from django.core.mail import send_mail,EmailMultiAlternatives
from PIL import Image,ImageDraw,ImageFont
import random,os,io
# 引入序列化加密
from itsdangerous import TimedJSONWebSignatureSerializer as Tjws,SignatureExpired
from django.core.cache import cache

# Create your views here.

def login(request):
    if request.method == "GET":
        return render(request,'vote/login.html')
    else:
        username=request.POST.get('login_name')
        pwd=request.POST.get('login_pwd')
        verifycode=request.POST.get('verify')
        # 妖cache储存数据
        if verifycode == cache.git('verifycode'):
        #     用session
        # if verifycode==request.ses储存数据sion.get('verifycode'):
            # user=authenticate(request,username=username,password=pwd)
            user = get_object_or_404(MyUser, username=username)
            if not user.is_active:
                return render(request, 'vote/login.html', {"error": "用户尚未激活"})
            else:
                check = user.check_password(pwd)
                if check:
                    lgi(request, user)
                    print(check, '????????')
                    return redirect(reverse('vote:index'))
                else:
                    return render(request, 'vote/login.html', {"error": "用户名或密码错误"})
        else:
            return render(request,'vote/login.html',{'error':'验证码错误'})

    # if user:
    #     if user.is_active:
    #         lgi(request,user)
    #         return redirect(reverse('vote:index'))
    #     else:
    #         return render(request, 'vote/login.html', {"error": "用户尚未激活"})
    # # return HttpResponseRedirect(request,'/vote/index/%s'%(id,))
    # else:
    #     error=None
    #     error="用户名或者密码错误"
    #     return render(request,'vote/login.html',{"error":error})
    # if request.method == "GET":
    #     return render(request, 'vote/login.html')
    # else:
    #     username = request.POST.get("username")
    #     if username == "zzy":
    #         # 登录成功之后需要将用户相关cookie存储
    #         res = redirect(reverse('vote:index'))
    #         # 设置cookit完成登录
    #         # res.set_cookie("username", username)
    #         # 通过session完成登录
    #         request.session["username"] = username
    #         return request
    #     else:
    #         return render(request, 'vote/login.html', {"error": "用户名错误"})

def logout(request):
    res = redirect(reverse('vote:login'))
    request.session.flush()
    return res

def register(request):

    if request.method=='POST':
        username=request.POST.get('regis_name')
        pwd=request.POST.get('regis_pwd')
        pwd2 = request.POST.get('regis_pwd1')
        email=request.POST.get('email')
        print(username,pwd,pwd2)
        error=None
        if pwd!=pwd2:
            error = "密码不一致"
            return render(request,'vote/login.html',{"error":error})
        else:
            user=MyUser.objects.create_user(username=username,password=pwd)
            print(user.id,user.is_active)
            user.is_active=False
            user.save()
            url='<a href='+"http:127.0.0.1:8000/vote/active/%s/"%(user.id)+'>点击激活</a>'
            #
            # send_mail('激活账号',url,settings.DEFAULT_FROM_EMAIL,[email])
            # 加密激活地址   加入有效期的序列化
            # de得到序列化工具
            serutil=Tjws(settings.SECRET_KEY,expires_in=600)
            # 使用序列化工具对字典序列化    加密
            result=serutil.dumps({"userid":user.id}).decode("utf-8")
            print(result,type(result),'_____________________________________')
            # try:
            #     obj=serutil.loads(result)
            #     print("________________",obj['userid'],"________")
            # except SignatureExpired as e:
            #     return HttpResponse('验证过期')

            mail=EmailMultiAlternatives('激活账号','<a href=http://127.0.0.1:8000/vote/active/%s/>点击激活</a>'%(result),settings.DEFAULT_FROM_EMAIL,[email])
            mail.content_subtype='html'
            mail.send()
            return render(request,'vote/login.html',{"error":"请在一小时之内激活"})
def active(request,info):
    serutil = Tjws(settings.SECRET_KEY, expires_in=600)
    try:
        obj = serutil.loads(info)
        print("________________", obj['userid'], "________")
        id=obj["userid"]

        user = get_object_or_404(MyUser, pk=id)
        user.is_active = True
        user.save()
        return redirect(reverse('vote:login'))
    except SignatureExpired as e:
        return HttpResponse('验证过期')

def verify(request):
    # 构造动态的验证码，用pillow构造图像，并返回前端页面
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    heigth = 40
    # 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        # 随机取得位置
        xy = (random.randrange(0, width), random.randrange(0, heigth))
    #     随机取得颜色
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
    # 填充小点
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    print(rand_str)
    # 构造字体对象
    # font = ImageFont.truetype('SCRIPTBL.TTF', 23)
    # fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    # draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    # draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    # draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    # draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    draw.text((5, 2), rand_str[0])
    draw.text((25, 2), rand_str[1])
    draw.text((50, 2), rand_str[2])
    draw.text((75, 2), rand_str[3])
    # 释放画笔
    del draw
    cache.set['verifycode',rand_str,500]


    request.session['verifycode'] = rand_str
    f = io.BytesIO()
    im.save(f, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')

def checkuser(request):
    if request.method=='POST':
        login_name=request.POST.get('login_name')
        print(login_name)
        if MyUser.objects.filter(login_name=login_name).first():
            return HttpResponse("用户存在")
        else:
            return HttpResponse("用户bu存在")


def change_pwd(request):
    if request.method=="GET":
        return render(request,'vote/change_pwd.html',locals())

@checklogin
def index(request):
    user=request.POST.get('username')
    # username = request.session.get('username')
    questions = VoteInfo.objects.all()
    return render(request,'vote/index.html', locals())

@checklogin
def index(request):
    # contex={'username':'zwj'}
    contex={}
    return render(request,"vote/index.html",contex)

@checklogin
def list(request):
    allvote=VoteInfo.objects.all()
    contex = {'allvote':allvote}
    return render(request, "vote/list.html", contex)

@checklogin
def detail(request,id):
    vote=VoteInfo.objects.get(pk=id)
    contex = {"vote": vote}
    if request.method == "GET":
        return render(request, "vote/detail.html", contex)
    elif request.method == "POST":
        x = request.POST['choose']
        x=int(x)
        print(x,type(x))
        if x==1:
            vote.choose1vote+=1
        else:
            vote.choose2vote+=1
        vote.save()
        print(vote.id, "____________________________--")
        return HttpResponseRedirect('/vote/result/%s/'%(id,))

@checklogin
def result(request, id):
    vote = VoteInfo.objects.get(pk=id)
    # print(vote.id,'__________________________________')
    c = {'vote': vote}
    return render(request, "vote/result.html",c)
    # return HttpResponse('ok-Ok-OK')

    # vote.matter=VoteInfo.objects.get(vote.matter)
    # print(vote.matter)
    # vote.choose1 = VoteInfo.objects.get(vote.choose1)
    # vote.choose2 = VoteInfo.objects.get(vote.choose2)
    # vote.choose1vote = VoteInfo.objects.get(vote.choose1vote)
    # vote.choose2vote = VoteInfo.objects.get(vote.choose2vote)
    # return render(request, "vote/result.html/%s/"%(id,))

def suggest(request):
    return redirect(reverse('vote:suggest'))

demo2/templates/vote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %} {% endblock %}</title>

</head>
<body>
<h2>58同城</h2>

<div>
    {% block div %}

    {% endblock %}
</div>

<h5>向我们提出建议<a href="#">联系客服</a></h5>
</body>
</html>

demo2/templates/vote/change_pwd.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div>

  <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#change_pwd" aria-controls="change" role="tab" data-toggle="tab">忘记密码</a>
            </li>

        </ul>

        <!-- Tab panes -->
        <div class="tab-content">


            {# ------------------------------------------------------------- #}
            <div role="tabpanel" class="tab-pane" id="register">

                <h2>忘记密码</h2>
                {{error}}
                <form class="form-horizontal" method="post" action="{% url 'vote:change_pwd' %}">
                     {% csrf_token %}
                    <div class="form-group">
                        <label for="ch_user" class="col-sm-2 control-label">用户名：</label>
                        <div class="col-sm-10">
                            <input type="text" name="ch_name" class="form-control" id="ch_user" placeholder="请输入用户名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ch_pwd" class="col-sm-2 control-label">密码：</label>
                        <div class="col-sm-10">
                            <input type="password" name="change_pwd" class="form-control" id="ch_pwd" placeholder="请输入密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ch_pwd_1" class="col-sm-2 control-label">密码</label>
                        <div class="col-sm-10">
                            <input type="password" name="change_pwd1" class="form-control" id="ch_pwd_1" placeholder="请输入密码">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
</div>

</body>
</html>

demo2/templates/vote/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
    <div class="container">
        <h1>投票</h1>

        {% if vote %}
        <form action="#" method="POST">
            {{ vote.matter }}<br>
            <input type="radio" name="choose" value="1">{{ vote.choose1}}<br>
            <input type="radio" name="choose" value="2">{{ vote.choose2}}<br><input type="submit" value="提交">
        </form>
        {% else %}
            wu

        {% endif %}
        <a href="{%  url 'vote:index' %}">返回首页</a>
        <br>
        <a href="{% url 'vote:list' %}">返回列表页</a>


    </div>



</body>
</html>

demo2/templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <div class="container">
        <h1>欢迎来到投票家园</h1>
        {{ request.user }}<br>

        <a href="{% url 'vote:login' %}">登录</a><a href="{% url 'vote:logout' %}">退出</a>
        <br><br>
        <a href="{% url 'vote:list'%}">进入投票列表</a><br><br>
    </div>
    <a href="{% url 'vote:suggest' %}">建议</a>


</body>
</html>

demo2/templates/vote/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票列表</title>
</head>
<body>
    <div class="container">
        <h1>选择你的感兴趣的投票</h1>
    <br>
            {% if allvote %}
        <ul>
            {% for vote in allvote %}
                <li><a href="/vote/detail/{{vote.id}}/">{{ vote.matter }}</a></li>
            {% empty %}

            {%  endfor %}
        </ul>
            {% else %}
            {% endif %}

    <a href="{% url 'vote:index'%}">返回首页</a>
    </div>

</body>
</html>

demo2/templates/vote/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div>

  <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">login</a>
            </li>
            <li role="presentation"><a href="#register" aria-controls="register" role="tab" data-toggle="tab">register</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
                <h2>登录</h2>
                {{error}}
                <form class="form-horizontal" method="post" action="#">
                     {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-10">
                            <input type="text" name="login_name" class="form-control" id="username" placeholder="请输入用户名">
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <input type="password" name="login_pwd" class="form-control" id="password" placeholder="请输入密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="verify" class="col-sm-2 control-label">验证码</label>
                        <div class="col-sm-2">
                            <img src="{% url 'vote:verify' %}" alt="" width="100" height="35">
                        </div>
                        <div class="col-sm-4">
                            <input type="text" name="verify" class="form-control" id="verify" placeholder="请输入验证码">
                        </div>
                    </div>


                                                <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                  <div class="checkbox">
                                    <label>
                                        <a href="{% url 'vote:change_pwd' %}">忘记密码</a>
                                    </label>
                                  </div>
                                </div>
                              </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">登录</button>

                            <span id="convertdata" class="btn btn-success">测试</span>

                            <div id="info">kong</div>
                        </div>
                    </div>
                </form>

            </div>

            <script>

                $(function(){
                    $('#convertdata').click(function(){
                        $.ajax({
                            url:'/vote/checkuser/',
                            type:'post',
                            data:{'login_name':$('#login_name').val(),
                            "csrfmiddlewaretoken": {{ csrf_token }}
                            },
                            success:function(data){
                                console.log(data);

                            }
                        })

                    })

                })





            </script>

            {# ------------------------------------------------------------- #}
        <div role="tabpanel" class="tab-pane" id="register">

            <h2>注册</h2>
            {{error}}
            <form class="form-horizontal" method="post" action="{% url 'vote:register' %}">
                 {% csrf_token %}
                <div class="form-group">
                    <label for="regis_username" class="col-sm-2 control-label">用户名：</label>
                    <div class="col-sm-10">
                        <input type="text" name="regis_name" class="form-control" id="regis_username" placeholder="请输入用户名">
                    </div>
                </div>

                <div class="form-group">
                    <label for="regis_pwd" class="col-sm-2 control-label">密码：</label>
                    <div class="col-sm-10">
                        <input type="password" name="regis_pwd" class="form-control" id="regis_pwd" placeholder="请输入密码">
                    </div>
                </div>

                <div class="form-group">
                    <label for="regis_pwd_1" class="col-sm-2 control-label">确认密码：</label>
                    <div class="col-sm-10">
                        <input type="password" name="regis_pwd1" class="form-control" id="regis_pwd_1" placeholder="请输入密码">
                    </div>

                 <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">邮箱：</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="email" placeholder="请输入邮箱">
                    </div>
                 </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">注册</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
</div>

</body>
</html>

demo2/templates/vote/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
</head>
<body>
    <div class="container">
        <b2>该投票历史结果为</b2>
        {% if vote %}
        {{ vote.matter }}<br>
        {{ vote.choose1 }}--{{  vote.choose1vote }}<br>
        {{ vote.choose2 }}--{{  vote.choose2vote }}<br>
        {% else %}
        {% endif %}

    </div>
</body>
</html>

demo2/templates/vote/suggest.html
{ % extends 'vote/base.html' % }

{% block title %}
建议
{% endblock %}

{% block div %}
<div>
    <li>helloworld</li>
</div>
{% endblock %}