demo5/blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    url(r'^indexone/$',views.indexone,name='indexone'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^about/$',views.about,name='about'),
    # url(r'^contact/$',views.contact,name='contact'),
    url(r'^categories/(\d+)/$',views.categories,name='categories'),
    url(r'^tags/(\d+)/$',views.tags,name='tags'),
    url(r'^contact/$',views.Contact.as_view(),name='contact'),
    url(r'^index/$',views.index,name='index'),
]

demo5/demo5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'search/', include('haystack.urls')),

    url('blog/',include('blog.urls',namespace='blog')),

]

demo5/blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Categories(models.Model):
    title=models.CharField(max_length=20,verbose_name='分类')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "分类"
        verbose_name_plural = verbose_name

class Tag(models.Model):
    title = models.CharField(max_length=20,verbose_name='标签')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "标签"
        verbose_name_plural = verbose_name

class Dynamic(models.Model):
    title = models.CharField(max_length=50,verbose_name='标题')
    body = models.TextField(verbose_name='内容')
    img=models.ImageField(upload_to='DynamicPicture',verbose_name='动态配图')
    views = models.PositiveIntegerField(default=0,verbose_name='阅读数')
    categories=models.ForeignKey(Categories,on_delete=models.CASCADE,verbose_name='分类')
    tag=models.ManyToManyField(Tag,verbose_name='标签')
    release_time=models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "文章"
        verbose_name_plural = verbose_name

demo5/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse,HttpResponse
from . models import Categories,Tag,Dynamic
from django.core.paginator import Paginator
from django.views.generic import View
from django.core.mail import send_mail,send_mass_mail
from django.core.mail import settings
# Create your views here.

def index(request):
    pagenum=request.GET.get('page')
    if pagenum==None:
        pagenum=1
    else:
        pagenum=pagenum
    dynamics=Dynamic.objects.all().order_by('-views')
    paginator=Paginator(dynamics,9)
    page=paginator.get_page(pagenum)

    return render(request,'blog/index.html',{'page':page})

def indexone(request):
    pagenum = request.GET.get('page')
    if pagenum == None:
        pagenum = 1
    else:
        pagenum = pagenum
    dynamics=Dynamic.objects.all().order_by('-views')
    paginator = Paginator(dynamics, 9)
    page = paginator.get_page(pagenum)
    return render(request, 'blog/homepage-2.html',{'page':page})

def detail(request,id):
    dynamic=get_object_or_404(Dynamic,pk=id)
    return render(request,'blog/blog-single.html',locals())

def about(request):
    return render(request,'blog/about.html')

class Contact(View):
    def get(self,request):
        return render(request, 'blog/contact.html',locals())
    def post(self,request):
        send_mail("测试邮件", "dashduahduasdjaisdhauihd", settings.DEFAULT_FROM_EMAIL, ['1120648012@qq.com', "275445831@qq.com"])
        msg=''
        return render(request,'blog/contact.html',{'msg':'发送成功'})


def categories(request,id):

    pagenum = request.GET.get('page')
    if pagenum == None:
        pagenum = 1
    else:
        pagenum = pagenum
    # return HttpResponse('success')
    dynamics= get_object_or_404(Categories, pk=id).dynamic_set.all()

    paginator = Paginator(dynamics, 6)
    page = paginator.get_page(pagenum)
    return render(request, 'blog/homepage-2.html', {'page': page})


def tags(request, id):
    pagenum = request.GET.get('page')
    if pagenum == None:
        pagenum = 1
    else:
        pagenum = pagenum
    dynamics = get_object_or_404(Tag, pk=id).dynamic_set.all()
    paginator = Paginator(dynamics, 6)
    page = paginator.get_page(pagenum)
    return render(request, 'blog/homepage-2.html', {'page': page})

demo5/templates/blog/about.html
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Parsa | about Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="/static/plugins/bootstrap/bootstrap.min.css">
  <!-- slick slider -->
  <link rel="stylesheet" href="/static/plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="/static/plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="/static/css/style.css" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/static/images/favicon.ico" type="image/x-icon">

</head>

<body>
  <!-- preloader -->
  <div class="preloader">
    <div class="loader">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- /preloader -->

<header class="navigation">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'blog:about' %}"><img class="img-fluid" src="/static/images/logo.png" alt="parsa"></a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
                aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navogation">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        主页
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'blog:index' %}">主页</a>
                        <a class="dropdown-item" href="{% url 'blog:indexone' %}">副页</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:about' %}">介绍</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:detail' 12 %}">文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:contact' %}">建议</a>
                </li>
            </ul>
            <form class="form-inline position-relative ml-lg-4" method="get" action="/search/" id="searchform">

                <input class="form-control px-0 w-100" type="search" placeholder="查询" required name="q">
                <button class="search-icon" type="submit"><i class="ti-search text-dark"></i></button>
            </form>
        </div>
    </nav>
</header>

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="mb-4">简介</h2>
        <img src="/static/images/author.jpg" alt="author" class="img-fluid w-100 mb-4">
        <h3 class="font-weight-light">您好<span class="font-weight-bold">我是不二大叔</span></h3>
        <p>微博2018十大影响力情感大V 知名情感博主 头条文章作者 微博签约自媒  <p>
          <p>诚接各种广告  </p>
          <p>联系电话：17737713663</p>
          <p>邮箱：shoujut@163.com/27445831@qq.com</p>
    </div>
  </div>
      </div>

</section>


<!-- instagram -->
<section>
  <div class="container-fluid px-0">
    <div class="row no-gutters instagram-slider" id="instafeed" data-userId="4044026246"
      data-accessToken="4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"></div>
  </div>
</section>
<!-- /instagram -->

<footer>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <a href="{% url 'blog:about' %}"><img src="/static/images/logo.png" alt="persa" class="img-fluid"></a>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">郑州</li>
                        <li class="font-secondary text-dark">红旗路-东三街-先锋商务3楼</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">17737713663</li>
                        <li class="font-secondary text-dark">shoujut@163.com</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <span class="font-secondary text-dark mr-3">转发</span>
                    <ul class="list-inline d-inline-block">
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-twitter-alt"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="text-center">
        <p>Copyright ©
            <script>var CurrentYear = new Date().getFullYear()
    document.write(CurrentYear)
            </script>
            a theme by themefisher / More Templates <a href="http://qikuedu.com/" target="_blank"
                                                       title="模板之家">奇酷出品</a> - Collect from <a
                    href="http://qikuedu.com/" title="网页模板" target="_blank">来自-手鞠</a></p>
    </div>
</footer>

<!-- jQuery -->
<script src="/static/plugins/jQuery/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="/static/plugins/bootstrap/bootstrap.min.js"></script>
<!-- slick slider -->
<script src="/static/plugins/slick/slick.min.js"></script>
<!-- masonry -->
<script src="/static/plugins/masonry/masonry.js"></script>
<!-- instafeed -->
<script src="/static/plugins/instafeed/instafeed.min.js"></script>
<!-- smooth scroll -->
<script src="/static/plugins/smooth-scroll/smooth-scroll.js"></script>
<!-- headroom -->
<script src="/static/plugins/headroom/headroom.js"></script>
<!-- reading time -->
<script src="/static/plugins/reading-time/readingTime.min.js"></script>

<!-- Main Script -->
<script src="/static/js/script.js"></script>

</body>
</html>

demo5/templates/blog/blog-single.html
{% load extend_fun %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Parsa | single Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="/static/plugins/bootstrap/bootstrap.min.css">
  <!-- slick slider -->
  <link rel="stylesheet" href="/static/plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="/static/plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="/static/css/style.css" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/static/images/favicon.ico" type="image/x-icon">

</head>

<body>

  <!-- preloader -->
  <div class="preloader">
    <div class="loader">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- /preloader -->

<header class="navigation">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'blog:about' %}"><img class="img-fluid" src="/static/images/logo.png" alt="parsa"></a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
                aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navogation">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        主页
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'blog:index' %}">主页</a>
                        <a class="dropdown-item" href="{% url 'blog:indexone' %}">副页</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:about' %}">介绍</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:detail' 12 %}">文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:contact' %}">建议</a>
                </li>
            </ul>
            <form class="form-inline position-relative ml-lg-4" method="get" action="/search/" id="searchform">

                <input class="form-control px-0 w-100" type="search" placeholder="查询" required name="q">
                <button class="search-icon" type="submit"><i class="ti-search text-dark"></i></button>
            </form>
        </div>
    </nav>
</header>

<!-- page-title -->
<section class="section bg-secondary">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4>{{ dynamic.title }}</h4>
      </div>
    </div>
  </div>
</section>
<!-- /page-title -->

<!-- blog single -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <ul class="list-inline d-flex justify-content-between py-3">
          <li class="list-inline-item"><i class="ti-user mr-2"></i>来自{{ dynamic.author }}</li>
          <li class="list-inline-item"><i class="ti-calendar mr-2"></i>{{ dynamic.release_time }}</li>
        </ul>
        <img src="/static/media/{{dynamic.img}}" alt="post-thumb" class="w-100 img-fluid mb-4">
        <div class="content">
          <p>{{ dynamic.body }}</p>
        </div>
      </div>
      <div class="col-lg-4">


          <form class="form-inline position-relative ml-lg-4" method="get" action="/search/" id="searchfor">

                <input class="form-control px-0 w-100" type="search" placeholder="Search" required name="q">
                <button class="search-icon" type="submit"><i class="ti-search text-dark"></i></button>
            </form>

        <div class="widget">
          <h6 class="mb-4">最近更新</h6>
          {% getlaterdynamics 3 as laterdynamics %}
            {% for laterdynamic in laterdynamics %}
              <div class="media mb-4">
            <div class="post-thumb-sm mr-3">
              <img class="img-fluid" src="/static/media/{{laterdynamic.img}}" alt="post-thumb">
            </div>
            <div class="media-body">
              <ul class="list-inline d-flex justify-content-between mb-2">
                <li class="list-inline-item">{{ laterdynamic.author }}</li>
                <li class="list-inline-item">{{ laterdynamic.release_time }}</li>
              </ul>
              <h6><a class="text-dark" href="{% url 'blog:detail' laterdynamic.id %}">{{ laterdynamic.body|myslice:16 }}</a></h6>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="widget">
          <h6 class="mb-4">TAG</h6>
          <ul class="list-inline tag-list">
              {% gettags as tags %}
              {% for tag in tags %}
                  <li class="list-inline-item m-1"><a href="{% url 'blog:tags' tag.id %}">{{ tag.title }}</a></li>
              {% endfor %}

          </ul>
        </div>
        <div class="widget">
          <h6 class="mb-4">CATEGORIES</h6>
          <ul class="list-inline tag-list">
            {% getcategories as categories %}
            {% for category in categories %}
                <li class="list-inline-item m-1"><a href="{% url 'blog:categories' category.id %}">{{ category.title }}</a></li>

            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /blog single -->

<footer>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <a href="{% url 'blog:about' %}"><img src="/static/images/logo.png" alt="persa" class="img-fluid"></a>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">郑州</li>
                        <li class="font-secondary text-dark">红旗路-东三街-先锋商务3楼</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">17737713663</li>
                        <li class="font-secondary text-dark">shoujut@163.com</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <span class="font-secondary text-dark mr-3">转发</span>
                    <ul class="list-inline d-inline-block">
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-twitter-alt"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="text-center">
        <p>Copyright ©
            <script>var CurrentYear = new Date().getFullYear()
    document.write(CurrentYear)
            </script>
            a theme by themefisher / More Templates <a href="http://qikuedu.com/" target="_blank"
                                                       title="模板之家">奇酷出品</a> - Collect from <a
                    href="http://qikuedu.com/" title="网页模板" target="_blank">来自-手鞠</a></p>
    </div>
</footer>

<!-- jQuery -->
<script src="/static/plugins/jQuery/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="/static/plugins/bootstrap/bootstrap.min.js"></script>
<!-- slick slider -->
<script src="/static/plugins/slick/slick.min.js"></script>
<!-- masonry -->
<script src="/static/plugins/masonry/masonry.js"></script>
<!-- instafeed -->
<script src="/static/plugins/instafeed/instafeed.min.js"></script>
<!-- smooth scroll -->
<script src="/static/plugins/smooth-scroll/smooth-scroll.js"></script>
<!-- headroom -->
<script src="/static/plugins/headroom/headroom.js"></script>
<!-- reading time -->
<script src="/static/plugins/reading-time/readingTime.min.js"></script>

<!-- Main Script -->
<script src="/static/js/script.js"></script>

</body>
</html>

demo5/templates/blog/contact.html
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Parsa | contant Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="/static/plugins/bootstrap/bootstrap.min.css">
  <!-- slick slider -->
  <link rel="stylesheet" href="/static/plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="/static/plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="/static/css/style.css" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/static/images/favicon.ico" type="image/x-icon">

</head>

<body>
  <!-- preloader -->
  <div class="preloader">
    <div class="loader">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- /preloader -->

<header class="navigation">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'blog:about' %}"><img class="img-fluid" src="/static/images/logo.png" alt="parsa"></a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
                aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navogation">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        主页
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'blog:index' %}">主页</a>
                        <a class="dropdown-item" href="{% url 'blog:indexone' %}">副页</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:about' %}">介绍</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:detail' 12 %}">文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase text-dark" href="{% url 'blog:contact' %}">建议</a>
                </li>
            </ul>
             <form class="form-inline position-relative ml-lg-4" method="get" action="/search/" id="searchform">

                <input class="form-control px-0 w-100" type="search" placeholder="查询" required name="q">
                <button class="search-icon" type="submit"><i class="ti-search text-dark"></i></button>
            </form>

        </div>
    </nav>
</header>

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="mb-4">联系我们</h2>
        <img src="/static/images/contact.jpg" alt="author" class="img-fluid w-100 mb-4">
        <p class="mb-5">Strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream and, as I lie close to the earth, a thousand unknown plants are noticed by me.<br><br>When I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains.</p>
        <form action="{% url 'blog:contact' %}" class="row" method="post">
            {% csrf_token %}
          <div class="col-lg-6">
            <input type="text" class="form-control mb-4" name="name" id="name" placeholder="Name">
          </div>
          <div class="col-lg-6">
            <input type="email" class="form-control mb-4" name="email" id="email" placeholder="Email">
          </div>
          <div class="col-12">
            <textarea name="message" id="message"  class="form-control mb-4" placeholder="Message..."></textarea>
          </div>
          <div class="col-12">
            <button class="btn btn-primary">发送</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<!-- instagram -->
<section>
  <div class="container-fluid px-0">
    <div class="row no-gutters instagram-slider" id="instafeed" data-userId="4044026246"
      data-accessToken="4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"></div>
  </div>
</section>
<!-- /instagram -->

<footer>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <a href="{% url 'blog:about' %}"><img src="/static/images/logo.png" alt="persa" class="img-fluid"></a>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">郑州</li>
                        <li class="font-secondary text-dark">红旗路-东三街-先锋商务3楼</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <ul class="list-unstyled">
                        <li class="font-secondary text-dark">17737713663</li>
                        <li class="font-secondary text-dark">shoujut@163.com</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 mb-4 mb-md-0">
                    <span class="font-secondary text-dark mr-3">转发</span>
                    <ul class="list-inline d-inline-block">
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-twitter-alt"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="text-center">
        <p>Copyright ©
            <script>var CurrentYear = new Date().getFullYear()
    document.write(CurrentYear)
            </script>
            a theme by themefisher / More Templates <a href="http://qikuedu.com/" target="_blank"
                                                       title="模板之家">奇酷出品</a> - Collect from <a
                    href="http://qikuedu.com/" title="网页模板" target="_blank">来自-手鞠</a></p>
    </div>
</footer>

<!-- jQuery -->
<script src="/static/plugins/jQuery/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="/static/plugins/bootstrap/bootstrap.min.js"></script>
<!-- slick slider -->
<script src="/static/plugins/slick/slick.min.js"></script>
<!-- masonry -->
<script src="/static/plugins/masonry/masonry.js"></script>
<!-- instafeed -->
<script src="/static/plugins/instafeed/instafeed.min.js"></script>
<!-- smooth scroll -->
<script src="/static/plugins/smooth-scroll/smooth-scroll.js"></script>
<!-- headroom -->
<script src="/static/plugins/headroom/headroom.js"></script>
<!-- reading time -->
<script src="/static/plugins/reading-time/readingTime.min.js"></script>

<!-- Main Script -->
<script src="/static/js/script.js"></script>

</body>
</html>