demo4/blog/urls.py
from django.conf.urls import url
from . import views
from . import feed
app_name='blog'
urlpatterns = [

    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^archives/(\d+)/(\d+)/',views.archives,name='archives'),
    url(r'^category/(\d+)/$',views.category,name='category'),
    url(r'^tag/(\d+)/$',views.tag,name='tag'),
    url(r'^rss/$',feed.BlogFeed(),name='rss'),
    # url(r'^contactus/$',views.contactus,name='contactus'),
    url(r'^contactus/$',views.Contacts.as_view(),name='contactus'),
    url(r'^addads/$',views.Adds.as_view(),name='addads'),
    url(r'^$',views.index,name='index'),
    ]

demo4/comment/urls.py
from django.conf.urls import url
from . import views
app_name='comment'

urlpatterns = [
    url(r'^addcomment/(\d+)/$', views.AddComment.as_view(), name='addcomment' ),
    ]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),

    url('comment/',include('comment.urls',namespace='comment')),


    url('',include('blog.urls',namespace='blog')),
]

demo4/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=30,verbose_name='分类')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "分类"
        verbose_name_plural = verbose_name

class Tag(models.Model):
    title=models.CharField(max_length=30,verbose_name='标签')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "标签"
        verbose_name_plural = verbose_name

class Article(models.Model):
    title=models.CharField(max_length=30,verbose_name='标题')
    body=models.TextField(verbose_name='内容')
    create_time=models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    update_time=models.DateTimeField(auto_now=True,verbose_name='更新时间')
    views=models.PositiveIntegerField(default=0,verbose_name='浏览次数')
    category=models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='分类')
    tags=models.ManyToManyField(Tag,verbose_name='标签')
    auther=models.ForeignKey(User,models.CASCADE,verbose_name='作者')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "文章"
        verbose_name_plural = verbose_name

class MessageInfo(models.Model):
    username=models.CharField(max_length=30)
    email=models.EmailField(blank=True,null=True)
    subject=models.CharField(max_length=50)
    # bushi 不是Django的原生类型
    info=HTMLField()

class Ads(models.Model):
    img=models.ImageField(upload_to='ads',verbose_name='广告图片')
    desc=models.CharField(max_length=30,verbose_name='图片描述')
    def __str__(self):
        return self.desc


    class Meta():
        verbose_name='轮播图'
        verbose_name_plural=verbose_name

demo4/comment/models.py
from django.db import models
from blog.models import Article
from datetime import datetime
# Create your models here.

class Comment(models.Model):
    title=models.CharField(max_length=50,verbose_name="评论")
    email=models.EmailField(blank=True,null=True)
    url=models.URLField(blank=True,null=True)
    content=models.CharField(max_length=500)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    create_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "评论"
        verbose_name_plural = verbose_name

demo4/comment/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.Form):
    name=forms.CharField(required=True,label="输入名字", widget=forms.TextInput(attrs={"id":"id_name"}))
    email=forms.EmailField(required=True,label="输入邮箱", widget=forms.EmailInput(attrs={"id":"id_email"}))
    url=forms.URLField(label="输入主页",widget=forms.URLInput(attrs={"id":"id_url"}))
    comment=forms.CharField(required=True,label="输入评论",widget=forms.TextInput(attrs={"id":"id_comment"}))

demo4/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.http import HttpResponse
from .models import Article,Category,Tag,MessageInfo,Ads
import markdown
from comment. forms import CommentForm
from django.views.generic import View
# 分页器
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def index(request):
    pagenum=request.GET.get('page')
    # pagenum=1 if pagenum==None else pagenum
    if pagenum==None:
        pagenum=1
    else:
        pagenum=pagenum
    articles=Article.objects.all().order_by('-views')
    print(pagenum)
    paginator=Paginator(articles,1)
    # 传入页码   得到页面    page包含所有信息
    page=paginator.get_page(pagenum)

    # latestarticle=Article.objects.all().order_by('-create_time')[:3]

    return render(request,'index.html',{'page':page})

def detail(request,id):
    article=get_object_or_404(Article,pk=id)
    article.views+=1
    # 确保body字段还没有更改   不然会报错
    article.save()
    # 处理body
    # 使用makedown 处理数据    将makedown语法转换为HTML标签
    # article.body=markdown.markdown(article.body,extensions=[
    #     'markdown.extensions.extra',
    #     'markdown.extensions.codehilite',
    #     'markdown.extensions.toc'
    #     ])

    # 方法2 外部使用目录  需要使用构造函数的写法
    mk=markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc'
        ])
    article.body=mk.convert(article.body)
    # 把makedown中的目录赋予TOC
    article.toc=mk.toc
    cf=CommentForm()
    # latestarticle = Article.objects.all().order_by('-create_time')[:3]
    return render(request,'single.html',locals())

def archives(request,year,month):
    articles=Article.objects.filter(create_time__year=year,create_time__month=month)
    paginator = Paginator(articles, 1)
    # 传入页码   得到页面    page包含所有信息
    page = paginator.get_page(1)
    return render(request, 'index.html', {'page': page})

def category(request,id):
    articles=get_object_or_404(Category,pk=id).article_set.all()
    paginator = Paginator(articles, 1)
    # 传入页码   得到页面    page包含所有信息
    page = paginator.get_page(1)
    return render(request, 'index.html', {'page': page})

def tag(request,id):
    articles = get_object_or_404(Tag, pk=id).article_set.all()
    paginator = Paginator(articles, 1)
    # 传入页码   得到页面    page包含所有信息
    page = paginator.get_page(1)
    return render(request, 'index.html', {'page': page})

class Contacts(View):
    def get(self,request):
        cf=CommentForm()
        return render(request, 'contact.html',locals())

    def post(self,request):
        # return HttpResponse('fasong')

        from django.conf import settings
        send_mail("Django邮件0", "Django可以发送邮件", settings.DEFAULT_FROM_EMAIL, ["1120648012@qq.com",'shoujut163.com'])
        return redirect(reverse('blog:contactus'))


class Adds(View):
    def get(self,request):
        return render(request,'addads.html')

    def post(self,request):
        img=request.FILES['img']
        desc=request.POST.get('desc')

        ad=Ads(img=img,desc=desc)
        ad.save()

        return redirect(reverse('blog:index'))

demo4/comment/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.views.generic import View
from django.http import HttpResponse
from .models import Comment
from blog.models import Article
from .forms import CommentForm
# Create your views here.


class AddComment(View):
    def post(self,request,id):
        print('======================')
        article=get_object_or_404(Article,pk=id)

        cf=CommentForm(request.POST)
        if cf.is_valid():
            title=cf.cleaned_data["name"]
            email = cf.cleaned_data['email']
            url = cf.cleaned_data['url']
            comment = cf.cleaned_data['comment']

        # title=request.POST.get('name')
        # email=request.POST.get('email')
        # url=request.POST.get('url')
        # comment=request.POST.get('comment')
            print(comment,'---------------------------')

            print("-------------")
            c=Comment()
            c.title=title
            print("-----------2222")
            c.email=email
            c.url=url
            c.content=comment
            c.article=article
            c.save()
            return redirect(reverse('blog:detail',args=(id,)))
        else:
            return HttpResponse('信息不合法')

demo4/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo4/templates/addads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加图片</title>
</head>
<body>
    <h2>添加轮播图</h2>
    <form action="{% url 'blog:addads' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    选择轮播图：<input type="file" name="img"><br>
    添加描述：<input type="text" name="desc"><br>
    <input type="submit" value="提交">
</form>
</body>
</html>

demo4/templates/base.html
{% load extend_fun %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title> {% block title %} {% endblock %} </title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>
<body id="page">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contactus' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">

                {% block toc %}

                {% endblock %}

                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestarticles 3 as latestarticles %}
                        {% for article in latestarticles %}
                        <li><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></li>
                        {% empty %}
                        <li>没有最近文章</li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getarchives as archives %}
                        {% for archive in archives %}
                            <li><a href="{% url 'blog:archives' archive.year archive.month  %}">{{ archive.year }} 年 {{ archive.month }} 月</a></li>
                        {% empty %}
                            <li>没有内容</li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as categorys %}
                        {% for category in categorys %}

                        <li><a href="{% url 'blog:category' category.id %}">{{ category.title}} </a><span class="post-count">({{ category.article_set.count }})</span></li>

                        {% endfor %}


                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for tag in tags %}
                        <li><a href="{% url 'blog:tag' tag.id %}">{{ tag.title }}</a></li>
                        {% empty %}
                        <li>没有标签</li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="{% url 'blog:contactus' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo4/templates/index.html
{% extends 'base.html' %}

{% load extend_fun %}

{% block left %}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

    {% getads as ads  %}


    <!-- Indicators -->
  <ol class="carousel-indicators">


      {% for ad in ads %}
        {% if forloop.counter == 1 %}
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter|add:-1 }}"></li>
        {% endif %}

      {% endfor %}

  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">



     {% for ad in ads %}
        {% if forloop.counter == 1 %}
            <div class="item active">
                <img src="/static/media/{{ ad.img }}" alt="...">
                <div class="carousel-caption">
                     {{ ad.desc }}
                </div>
            </div>
        {% else %}
            <div class="item">
             <img src="/static/media/{{ ad.img }}" alt="...">
                <div class="carousel-caption">
                    {{ ad.desc }}
                </div>
             </div>
        {% endif %}

      {% endfor %}
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% if page %}
{% for article in page.object_list %}
<article class="post post-{{ article.id }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ article.category.title }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                 datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ article.auther.username }}</a></span>
            <span class="comments-link"><a href="#">{{ article.comment_set.count }} 条评论</a></span>
            <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>
            {# {{ article.body|truncatechars:60 }}...... #}
            {# {{ article.body|lower|upper|join:'+' }} #}

            {{ article.body|myslice:30 }}

        </p>
        <div class="read-more cl-effect-14">
            <a href="{% url 'blog:detail' article.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{%  empty %}
<li>没有文章对象</li>
{% endfor %}

{% else %}
没有文章
{% endif %}



                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
<div class="pagination">
    <ul>
        {% if page.has_previous %}
            <li><a href="/?page={{page.previous_page_number}}">上一页</a></li>
        {% endif %}

        {% for num in page.paginator.page_range %}
        <li><a href="/?page={{num}}"> {{ num }} </a></li>

        {% endfor %}

        {% if page.has_next %}
            <li><a href="/?page={{page.next_page_number}}">下一页</a></li>
        {% endif %}
    </ul>
</div>
{% endblock %}

demo4/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜过结果</title>
</head>
<body>

    {{ query }}
    {% if query %}
        {% if page %}
            {% for article in page.object_list %}
                {{ article.object.title }}
            {% empty %}
                <li>无对象</li>
            {% endif %}
    {% endif %}
</body>
</html>

demo4/templates/single.html
{% extends 'base.html' %}

{% block left %}
<article class="post post-{{ article.id }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ article.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ article.category.title }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ article.auther.username }}</a></span>
            <span class="comments-link"><a href="#">{{ article.comment_set.count }} 条评论</a></span>
            <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ article.body|safe }}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comment:addcomment' article.id %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="id_name">名字：</label>
                {# <input type="text" id="id_name" name="name" required> 方法一  #}

                {{ cf.name }}
            </div>

            <div class="col-md-4">
                <label for="id_email">邮箱：</label>
               {#  <input type="email" id="id_email" name="email" required> #}
                {{ cf.email }}
            </div>
            <div class="col-md-4">
                <label for="id_url">网址：</label>
                {# <input type="text" id="id_url" name="url"> #}
                {{ cf.url }}
            </div>
            <div class="col-md-12">
                <label for="id_comment">评论：</label>
               {# <textarea name="comment" id="id_comment" required></textarea> #}
                {{ cf.comment }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">

            {% for c in article.comment_set.all %}
            <li class="comment-item">
                <span class="nickname">{{ c.title }}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ c.create_time }}</time>
                <div class="text">
                   {{ c.content }}
                </div>
            </li>
            {% empty %}
            <li>无评论内容</li>
            {% endfor %}


        </ul>
    </div>
</section>
{% endblock %}

{% block toc %}
<div class="widget widget-content">
<h3 class="widget-title">文章目录</h3>
   {{ article.toc|safe }}
</div>
{% endblock %}