demo1/booktest/urls.py
from django.conf.urls import url
from . import views


#
app_name="booktest"
urlpatterns = [
    url(r"^index/$",views.index,name="index"),
    url(r"^list/$",views.list,name="list"),
    url(r"^detail/(\d+)/$",views.detail,name="detail"),
    url(r"^deletebook/(\d+)/$",views.deletebook,name="deletebook"),
    url(r"^deletehero/(\d+)/$",views.deletehero,name="deletehero"),
    url(r"^addhero/(\d+)/$",views.addhero,name="addhero"),
    url(r"^updatehero/(\d+)/$",views.updatehero,name="updatehero"),
    url(r"^addbook/$",views.addbook,name="addbook"),
    url(r"^updatebook/(\d+)/$",views.updatebook,name="updatebook"),

]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
# 引入模块
from django.conf.urls import include,url
from django.http import HttpResponse

# 项目路由  所有浏览器的请求先进入项目路由
urlpatterns = [
    path('admin/', admin.site.urls),
    # 引入外部路由文件
    # 会截取URL里booktest字符串
    url("booktest/",include("booktest.urls",namespace="booktest")),
]

demo1/booktest/models.py
from django.db import models


# Create your models here.

class Bookinfo(models.Model):

    title=models.CharField(max_length=30,verbose_name="标题")
    pub_date=models.DateField(verbose_name="日期")

    def __str__(self):
        return self.title

GEBDLE=(("man","男"),("woman","女"))
class Heroinfo(models.Model):

    name=models.CharField(max_length=30,verbose_name="角色")
    gendle=models.CharField(max_length=10,choices=GEBDLE,verbose_name="性别")
    skill=models.CharField(max_length=30,null=True,verbose_name="技能")
    book=models.ForeignKey(Bookinfo,on_delete=models.CASCADE,verbose_name="书名")

    def __str__(self):
        return self.name


class ManageExt(models.Manager):

    def createtestmodel2(self,_title):
        t=self.model()
        t.title=_title
        t.save()

    def deletetestmodel2(self,_pk):
        self.get(pk=_pk).delete()


class TestModel(models.Model):
    title=models.CharField(max_length=20)
    manage=models.Manager()
    manage2=ManageExt()

    @classmethod
    def createtestmodel(cls,_title):
        t=cls(title=_title)
        t.title=_title
        t.save()

demo1/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Bookinfo,Heroinfo

# Create your views here.

def index(request):
    # return HttpResponse("index首页")
    #1 加载 得到一个模板
    # template=loader.get_template("booktest/index.html")
    #2 构造参数字典
    # contex={"username":"zwj"}
    #3 使用模板渲染动态数据
    # result=template.render(contex)
    #4 将返回数据给页面
    # return HttpResponse(result)
    # -----------------render简写------------------------
    contex = {"username": "zwj"}
    return render(request,"booktest/index.html",contex)
def list(request):
    # 查询所有书籍
    # allbook=Bookinfo.objects.all()
    # 加载 得到一个模板
    # templ=loader.get_template("booktest/list.html")
    # 使用模板渲染动态数据
    # contex = {"allbook":allbook}
    # result=templ.render({"allbook":allbook})
    # 将返回数据给页面
    # return HttpResponse(result)

    # -----------------render简写------------------------
    allbook = Bookinfo.objects.all()
    contex = {"allbook": allbook}
    return render(request,"booktest/list.html",contex)
def detail(request,id):
    # id代表书的主键，用主键找到这本书
    # return HttpResponse("当前为第%s页"%id)
    # book=None
    # try:    #获得书名【超链接】的ID  为list页面跳转做准备
    #     book=Bookinfo.objects.get(pk = id)
    # except Exception as e:
    #     return HttpResponse("没有这本书的信息")
    # 加载 得到一个模板
    # templ=loader.get_template("booktest/detail.html")
    # 使用模块渲染数据
    # result=templ.render({"book":book})
    # 将数据返回给页面
    # return HttpResponse(result)
    # -----------------render简写------------------------
    book=Bookinfo.objects.get(pk = id)
    context={"book":book}
    return render(request,"booktest/detail.html",context)

def deletebook(request,id):
    # return HttpResponse("success")
    # 删除英雄   通过书名的id删除
    Bookinfo.objects.get(pk=id).delete()
    # 返回已删除的书籍列表页面
    return HttpResponseRedirect(redirect_to="/booktest/list/")

def deletehero(request,id):
    # return HttpResponse("success")
    # 通过id获取永雄
    hero=Heroinfo.objects.get(pk=id)
    # 通过英雄获取书籍的id
    bookid=hero.book.id
    # 删除英雄
    hero.delete()
    # 返回已删除后英雄的界面         通过书籍的id进入该书籍的已删除的英雄列表
    return HttpResponseRedirect(redirect_to="/booktest/detail/%s/"%(bookid))

def addhero(request,id):
    # return HttpResponse("添加
    if request.method=="GET":
        return render(request,"booktest/addhero.html",{"bookid":id})
    elif request.method=="POST":
        book=Bookinfo.objects.get(pk=id)
        hero=Heroinfo()
        hero.name=request.POST["username"]
        value=request.POST["sex"]
        hero.gendle=value
        hero.skill=request.POST["skill"]
        hero.book=book
        hero.save()
        return HttpResponseRedirect("/booktest/detail/%s/"%(id,))

def updatehero(request,id):
    hero=Heroinfo.objects.get(pk=id)
    if request.method=="GET":
        return render(request,"booktest/updatehero.html",{"hero":hero})

    elif request.method=="POST":
        hero.name = request.POST["username"]
        hero.gendle= request.POST["sex"]
        hero.skill = request.POST["skill"]
        hero.save()
        return HttpResponseRedirect("/booktest/detail/%s/"%(hero.book.id))

def addbook(request):
    if request.method=="GET":
        return render(request,"booktest/addbook.html")
    elif request.method=="POST":
        print('post')
        book=Bookinfo()
        book.title=request.POST["bid"]
        book.pub_date=request.POST["time"]
        book.save()
        return HttpResponseRedirect("/booktest/list/")

def updatebook(request,id):
    book=Bookinfo.objects.get(pk=id)
    if request.method=="GET":
        return render(request,"booktest/updatebook.html",{"bookid":id})
    elif request.method=="POST":
        book.title = request.POST["bid"]
        book.pub_date = request.POST["time"]
        book.save()
        return HttpResponseRedirect("/booktest/list/")
    # return HttpResponse("修改成功")


        # return HttpResponse("添加成功")

demo1/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
            <h2>添加书籍</h2>
            <form action="{% url 'booktest:addbook'%}" method="post">
                <!--出自：<input type="text" disabled value="{{bookid.title}}"><br>-->
                书名：<input type="text" name="bid"><br>

                时间：<input type="text" name="time"><br>
                <input type="submit" value="提交">
            </form>
        </div>



</body>
</html>

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加角色</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>

    <div class="container">
        <h2>添加角色</h2>
        <form action="{% url 'booktest:addhero' bookid %}" method="post">
            <!--出自：<input type="text" disabled value="{{bookid.title}}"><br>-->
            角色名：<input type="text" name="username"><br>
            性别：<input type="radio" name="sex" value="men" >男<input type="radio" name="sex" value="women">女<br>
            技能：<input type="text" name="skill"><br>
            <input type="submit" value="提交">
        </form>
    </div>

</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
   <div class="container">
            <h2>详情页</h2>
        <br>

        {% if book %}
        {hero}
        <!--双括号一定加上不然会只显示book.title，，等于没有获取书名-->
        <h3>{{ book.title }}</h3>
        <ul>
            <!--遍历书籍内的角色-->
            {% for hero in book.heroinfo_set.all %}
                <li>{{ hero.name }}--{{ hero.gendle }}--{{ hero.skill }}<a href="{% url 'booktest:deletehero' hero.id %}">---删除</a><a href="{% url 'booktest:updatehero' hero.id %}">--修改</a></li>


            {% empty %}
                <li>没有英雄角色</li>

            {% endfor %}
        </ul>
        {% else %}
        没有书籍信息
        {% endif %}
       <a href="{% url 'booktest:addhero' book.id %}">添加英雄</a>
       <br>

        {# <a href="/booktest/list/">返回列表页</a> #}
        <a href="{% url 'booktest:list' %}">返回列表页</a>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img src="/static/img/a1.jpg" alt="" width="600" height="300">
   </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integ></script>

</head>
<body>
    <div class="container">
            <h2>首页</h2>
        {{ username }}
        <br>
        {# <a href="/booktest/list/">进入列表页</a> #}
        <a href="{% url 'booktest:list' %}">进入列表页</a>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="/static/img/hot1.jpg" alt="...">
              <div class="carousel-caption">
                像飞驰少年
              </div>
            </div>
            <div class="item">
              <img src="/static/img/hot2.jpg" alt="...">
              <div class="carousel-caption">
                万种童书
              </div>
            </div>
              <div class="item">
              <img src="/static/img/hot3.jpg" alt="...">
              <div class="carousel-caption">
                优选好书
              </div>
            </div>
              <div class="item">
              <img src="/static/img/hot4.jpg" alt="...">
              <div class="carousel-caption">
                优选好书
              </div>
            </div>
              <div class="item">
              <img src="/static/img/hot5.jpg" alt="...">
              <div class="carousel-caption">
                优选好书
              </div>
            </div>
              <div class="item">
              <img src="/static/img/hot6.jpg" alt="...">
              <div class="carousel-caption">
                优选好书
              </div>
            </div>
              <div class="item">
              <img src="/static/img/hot7.jpg" alt="...">
              <div class="carousel-caption">
                优选好书
              </div>
            </div>
            ...
          </div>


          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>
    <script>
        $('.carousel').carousel({
            interval: 1000
            })
    </script>



</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
            <h2>列表页</h2>
        {% if allbook %}
            <ul>
                {% for book in allbook %}
                <!--把书名做成一个超级链接 前边虚拟地址不变，后边加上以书名的主键作为虚拟地址 /booktest/detail/-->
                {# <li><a href="/booktest/detail/{{book.id}}/">{{ book.title }}</a></li> #}
                <li><a href="{% url 'booktest:detail' book.id %}">{{ book.title }}--{{ book.pub_date }}</a><a href="{% url 'booktest:deletebook' book.id %}">--删除</a><a
                        href="{% url 'booktest:updatebook' book.id %}">--修改</a></li>
                {% empty %}
                    无书籍信息
                {% endfor %}
            </ul>
        {% else %}

        {% endif %}
        <a href="{% url 'booktest:addbook'%}">添加书籍</a>

        <br>
        <a href="/booktest/index/">返回首页</a>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img src="/static/img/a1.jpg" alt="" width="600" height="300">
    </div>

</body>
</html>

demo1/templates/booktest/updatebook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>更新书籍</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
                <h2>修改书籍</h2>
                <form action="{% url 'booktest:updatebook' bookid %}" method="post">
                    <!--出自：<input type="text" disabled value="{{bookid.title}}"><br>-->
                    书名：<input type="text" name="bid" placeholder="{{book.title}}"><br>

                    时间：<input type="text" name="time" placeholder="{{ book.pub_date }}"><br>
                    <input type="submit" value="提交">
                </form>
            </div>

</body>
</html>

demo1/templates/booktest/updatehero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改角色</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h2>修改角色</h2>
        <form action="#" method="post">
            角色id：<input type="text" disabled value="{{hero.id}}"><br>
            角色名：<input type="text" name="username" placeholder="{{hero.name}}"><br>
            性别：
            {% if hero.gendle == "man" %}

            <input type="radio" name="sex" value="men" checked>男<input type="radio" name="sex" value="women">女<br>
            {% else %}

            <input type="radio" name="sex" value="men" >男<input type="radio" name="sex" value="women" checked>女<br>
            {% endif %}

            技能：<input type="text" name="skill" placeholder="{{hero.skill}}"><br>
            <input type="submit" value="提交">
        </form>
    </div>

</body>
</html>